
def shift (input, amount):
  output = list(input)
  j = 0
  while (j < len(output)):
    charcode = ord(output[j]) + amount
    output[j] = chr(charcode)
    j+=1
  #output.join ''
  return ''.join(output)

def encrypt (input, level):
  array = input.split('')
  output = []
  output[0] = array[array.length - 1]
  output[1] = array[array.length - 2]
  j = 0
  while (j < array.length - 2):
    output[j + 2] = array[j]
    j+=1
  #console.log("Just Swapped: " + output.join(""));
  output = shift(output.join(''), level).split('')
  output = output.reverse()
  j = 0
  while (j < output.length):
    output[j] = String.fromCharCode(output[j].charCodeAt() + level)
    j += 2
  return ''.join(output)


def decrypt (input, level):
  output = input.split('')
  j = 0
  while (j < output.length):
    output[j] = String.fromCharCode(output[j].charCodeAt() - level)
    j += 2
  output = output.reverse()
  output = shift(output.join(''), level * -1).split('')
  array = []
  array[output.length - 1] = output[0]
  array[output.length - 2] = output[1]
  j = 0
  while (j < array.length - 2):
    array[j] = output[j + 2]
    j+=1
  result = array.join('')
  return ''.join(array)

### Experimental ###

#Encrypts a string to a Shah Cipher with a specified shift level

def encryptShah (input, level):
  #`var j`
  array = list(input)
  output = [None] * len(array)
  last = 0
  index = 0
  #console.log 'Final Tier Encrypt: ' + array.join('')
  j = 0
  while (j < len(array)):
    #0246
    output[index] = array[j]
    index+=1
    j += 2
  j = 1
  while (j < len(array)):
    #1357
    output[index] = array[j]
    index+=1
    j += 2
  output = list(shift(''.join(output), level))
  output = output.reverse()
  return ''.join(output)

#Decrypts a Shah Cipher string for a shift level

def decryptShah (input, level):
  #`var j`
  array = input.split('')
  array = array.reverse()
  output = shift(array.join(''), level * -1).split('')
  #Works up to here
  array = output
  output = []
  index = 0
  temp = 0
  j = 0
  while (j < array.length):
    if not(index < array.length):
      #alert("break");
      break
    output[index] = array[j]
    index += 2
    temp = j
    j+=1
  index = 1
  temp+=1
  j = temp
  while (j < array.length):
    if not(index < array.length):
      break
    output[index] = array[j]
    index += 2
    j+=1
  return ''.join(output)
# generated by js2coffee 2.2.0
str = "hello"
print "Original: " + str
str = encryptShah (str, 10)
print "Encrypted: " + str
